# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
name: Test for PRs
# omitted, see above
jobs:
 sql-auth-tsqlt:
  name: Test installting tSQLt with SQL auth
  runs-on: ubuntu-latest
  services:
    sqlserver:
      image: mcr.microsoft.com/mssql/server:2019-latest
      ports:
        - 1433:1433
      env:
        ACCEPT_EULA: Y
        SA_PASSWORD: Verystrongindeed123!
  steps:
      - uses: actions/checkout@v2
      - name: CreateTargetDB
        run: docker exec -i $ENV_CONTAINER_ID /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Verystrongindeed123! -Q "CREATE DATABASE TargetDB"
      - name: Install tSQLt with SQL auth
        uses: lowlydba/tsqlt-installer@v1
        with:
          sql-instance: localhost
          database: TargetDB
          version: latest
          user: sa
          password: Verystrongindeed123!
